spring:
  application:
    name: RBox
  profiles:
    active: ${APP_ACTIVE_PROFILE:local}

sms:
  sid: ${SMS_ACCOUNT_SID}
  token: ${SMS_AUTH_TOKEN}
  from: ${SMS_FROM}
azure:
  cosmos:
    uri: ${COSMOS_URI:http://localhost:443/}
    key: ${COSMOS_KEY:root}
    database: ${COSMOS_DB:localdb}

delivery:
  from:
    name: "Indo Art In Style (IAIS)"
    address: "Sunanda Enclave, Opp Govt Girls HS School, Club Road, Silchar, Dist: Cachar, Assam, Pin: 788001"
    phoneno: 6001955236